const sizes = {
    base : 16,
    borderRadius: 8,
    marginAuto:"0 auto",
    marginTopComponent:"5rem",
    mediumGap:"2rem",
    ortaSizes:"20px",
    largeFontSize:"32px",
    productMainWidth:1216,
    productMainHeight:480,
    borderRadiusLarge:"32px",
    borderRadiusMedium:"28px",
    boxShadow: " rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;",
    productsSortWidth:228,
    productsSortHeight:56,
    activeSortWidth:228,
    activeSortHeight:56,
    zIndex:999999999,
    mediumPadding:"92px 0",
    lineHeight:"122%",
    footerFormPaddingTop:"15px",
    footerFormPaddingRight:"20px",
    marginTop:"9.5rem",
    borderRadiusveryLarge:"49px",
    inpPadding:"0.9rem",
    normalInptWidht:"560px",
    zero:0,
    smallMarginTop:"2rem",
    width: "1260px",
    componentPaddingTop:"13rem 0"
};

export default sizes;
